### ISSUE TITLE
rebloom needed for fixed rosdep on debian for  libjpeg 

### ISSUE THREAD

**Issue by tfoote** [ros-gbp/opencv3-release#1]
We imported ffmpeg from jessie-backports: https://github.com/ros/rosdistro/issues/10914 

We fixed the rosdep rule for libjpeg: https://github.com/ros/rosdistro/pull/10912

However the rosdep rule change for libjpeg needs bloom to be rerun to update the package dependencies in the debian sourcedebs.

**Comment by vrabaud** [comment]
fixed, thx.
