### ISSUE TITLE
Remove dependency on jasper

### ISSUE THREAD

**Issue by machinekoder** [ros-gbp/opencv3-release#19]
The library seems to be replaced with `libopenjp2` on Debian:
https://github.com/ros/rosdistro/issues/18173
https://packages.debian.org/search?keywords=libopenjp2-7

**Comment by mikaelarguedas** [comment]
@machinekoder this is not enough information. Please provide a full issue description, including your use case, the ROS distribution the issue is about and the motivation to remove the dependency.

**Comment by machinekoder** [comment]
Again, Kinetic on Debian Stretch, not supported, so I'll close this issue.
