### ISSUE TITLE
Opencv tracking.hpp not found 

### ISSUE THREAD

**Issue by onurtore** [ros-gbp/opencv3-release#4]
Hello me again, :D
I can't use opencv3 package with ros there is  problem with headers
 : fatal error: opencv2/tracking.hpp: No such file or directory   also there is no tracking.hpp in my system but ı download the package for opencv3
[here](https://github.com/onurtore/kcf_algorithm.git), i put my code    ı'm doing something wrong with cMakeList and package.xml but i have no idea, can you help me to fix it ?

**Comment by vrabaud** [comment]
This kind of question belongs to http://answers.ros.org/questions/
The code you provide has many mistakes (it lacks proper includes for cv_bridge for example). You also include OpenCV in your find_package(catkin), that should not be the case.
