### ISSUE TITLE
No gpu enabled feature

### ISSUE THREAD

**Issue by furushchev** [ros-gbp/opencv3-release#5]
If I install opencv3 via apt `ros-kinetic-opencv3`, there is no GPU enabled feature.
(e.g. header file `opencv2/cudaoptflow.hpp` is not found at `/opt/ros/kinetic/include/opencv-3.1.0-dev`)

- Is opencv3 provided from `apt-get` disabled gpu feature?
- Is there any way to support GPU feature of opencv3?

**Comment by vrabaud** [comment]
Not by default no. We would need to have OpenCV depend on CUDA packages right and that would be: http://packages.ubuntu.com/xenial/nvidia-cuda-dev
This does not work on 32 bit and ARM so we could not. You need to create your own package by patching the sources.

**Comment by furushchev** [comment]
@vrabaud Sorry for very late response. Thank you for information anyway!
