### ISSUE TITLE
OpenCV in Kinetic does not build on macOS Sierra

### ISSUE THREAD

**Issue by igilitschenski** [ros-gbp/opencv3-release#6]
Following up on a recommendation by @tfoote in ros/rosdistro#13298, I am posting this here:

There might be a need to make a new opencv3 release for making it compile under macOS Sierra as the current build produces a `'QTKit/QTKit.h' file not found` error which seems to be known (see e.g. Homebrew/homebrew-science#4104, opencv/opencv#6913) and already addressed in OpenCV by opencv/opencv#7159.

**Comment by agurusa** [comment]
+1

**Comment by vrabaud** [comment]
sorry for the delay, the latest version in rosdistro has the patch you requested so all should be fine.
